USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS RAW COMMENT = 'Landing zone';
CREATE DATABASE IF NOT EXISTS ANALYTICS COMMENT = 'dbt transformations';

CREATE SCHEMA IF NOT EXISTS RAW.CLIMATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.MARTS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.SNAPSHOTS;

CREATE TABLE IF NOT EXISTS RAW.CLIMATE.RAW_FORECAST (
    id            BIGINT AUTOINCREMENT PRIMARY KEY,
    raw_payload   VARIANT NOT NULL,
    file_name     STRING,
    loaded_at     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);