USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS LOADER_ROLE;
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE LOADER_ROLE;
GRANT USAGE ON DATABASE RAW TO ROLE LOADER_ROLE;
GRANT USAGE ON SCHEMA RAW.CLIMATE TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON TABLE RAW.CLIMATE.RAW_FORECAST TO ROLE LOADER_ROLE;

CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON ALL TABLES IN DATABASE ANALYTICS TO ROLE TRANSFORMER_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE TRANSFORMER_ROLE;

CREATE USER IF NOT EXISTS LOADER_USER
    PASSWORD = 'Loader_ChangeMe_Strong_2026!'
    DEFAULT_ROLE = LOADER_ROLE
    DEFAULT_WAREHOUSE = LOAD_WH
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE LOADER_ROLE TO USER LOADER_USER;

CREATE USER IF NOT EXISTS DBT_USER
    PASSWORD = 'Dbt_ChangeMe_Strong_2026!'
    DEFAULT_ROLE = TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE = TRANSFORM_WH
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE TRANSFORMER_ROLE TO USER DBT_USER;

-- Grant to your admin user for local dev
GRANT ROLE LOADER_ROLE TO USER ANASS56;
GRANT ROLE TRANSFORMER_ROLE TO USER ANASS56;